### ISSUE TITLE
How to set IColumnFilter using @DbUnit

### ISSUE THREAD

**Issue by Kanti1702** [janbols/spock-dbunit#10]
I have one of my table  without primary key, So I want to set IColumnFilter as per given example in [](http://dbunit.wikidot.com/noprimarykeytable)
So I have add below @DbUnit annoation to one of my feature:

@DbUnit(configure={ IDatabaseTester it ->
		it.getConnection().getConfig().setProperty(
				DatabaseConfig.PROPERTY_PRIMARY_KEY_FILTER,
				new MyPrimaryKeyFilter(null))
		it.setUpOperation = DatabaseOperation.REFRESH
		it.tearDownOperation = DatabaseOperation.NONE
	}, content = {
		tableWitoutPK(no_key1:value1, no_key2:value2)
	})
        def "add value to table without pk"(){
               .........
        }

class MyPrimaryKeyFilter implements IColumnFilter{
.........
}

But it's failing with exception: org.dbunit.dataset.NoPrimaryKeyException: tableWitoutPK

When I have debug, found that while configuring IDatabaseTester in DbUnitInterceptor it's throwing exception "Failed to instantiate tester configurer in @DbUnit".

I don't know this feature is present in current DbUnit extension or not.

**Comment by janbols** [comment]
Hi @Kanti1702 , I expect the problem you experiences was twofold:
1. when no `DbUnit` annotation exists on a field but only on features, the extension did not create the correct interceptors leading to a NPE
2. there was a bug reported in https://github.com/janbols/spock-dbunit/issues/9, that prevented you from specifying the connection configuration properties.

Both should be solve in the currenct version 0.4. So please take a look at them. I also added a test for your case that you can find back in https://github.com/janbols/spock-dbunit/blob/master/src/test/groovy/be/janbols/spock/extension.dbunit/Issue10Specification.groovy. Could you please check if this solves your problem.

Thanks for reporting the bug.

**Comment by Kanti1702** [comment]
Hey @janbols , I have tested above mentioned test cases and it's resolve my problem partially thank you for that.

But I have 1 concern, when I use DatabaseOperation.DELETE for tearDownOperation it's giving me exception: org.dbunit.dataset.NoPrimaryKeyException: tableWitoutPK

**Comment by janbols** [comment]
Hi @Kanti1702 , please check http://stackoverflow.com/questions/25912503/dbunit-throwing-nosuchcolumnexception-while-deleting-the-dataset or similar posts. I think this is a limitation of dbunit so there's not much I can do about this.
