### ISSUE TITLE
Qualified names support (multiple schemas)

### ISSUE THREAD

**Issue by okorz001** [janbols/spock-dbunit#12]
My project requires mocking data in multiple schemas (databases), so I am trying to us DbUnit's qualified table name feature. However, I am having problems with this so I am wondering if it has been tested before. 

I am able to enable the feature with the configure closure:

```groovy
@DbUnit(configure = {
    it.connection.config.setProperty(DatabaseConfig.FEATURE_QUALIFIED_TABLE_NAMES, true)
})
def content = {
  'FOO.BAR'(id: 1)
}
```

But inserting fails with an unknown table:

```
    org.dbunit.dataset.NoSuchTableException: FOO.BAR
```

I have verified the tables exist with a simple `SELECT *` query.

Disregard this part below; this issue was related to jooq and are not present using groovy sql.

~~~I am using H2 and I ran into some issues earlier when I was creating the tables (unrelated to spock-dbunit), so I also tried enabling an escape pattern but that had no effect:~~~

**Comment by okorz001** [comment]
I have added a test here which fails:
https://github.com/janbols/spock-dbunit/compare/master...okorz001:qualified-names?expand=1

**Comment by okorz001** [comment]
This may be an issue with dbunit itself and I am now trying to confirm how this feature works without spock-dbunit.

**Comment by okorz001** [comment]
Okay, I have confirmed that my initial attempts were invalid. Apparently the tester connection is transient, so instead of setting config directly on this we need to use an operation listener:

```groovy
        tester.operationListener = new DefaultOperationListener() {
            @Override
            void connectionRetrieved(IDatabaseConnection connection) {
                super.connectionRetrieved(connection);
                connection.config.setProperty(DatabaseConfig.FEATURE_QUALIFIED_TABLE_NAMES, true)
            }
        }
```

This works for me in a regular test calling DbUnit directly, but it is not working with the spock-dbunit configure closure:

```groovy
    @DbUnit(configure = {
        it.operationListener = new DefaultOperationListener() {
            @Override
            void connectionRetrieved(IDatabaseConnection connection) {
                super.connectionRetrieved(connection);
                connection.config.setProperty(DatabaseConfig.FEATURE_QUALIFIED_TABLE_NAMES, true)
            }
        }
    })
```

I have updated my test case accordingly.

**Comment by okorz001** [comment]
I see from #9 that spock-dbunit is using a special tester that has persistent connections, so the operation listener is not actually necessary with this library. I confirm that I see the setting enabled in the dbunit debug logging even with the original method (setting on the connection directly in the closure).

**Comment by janbols** [comment]
First, @okorz001 , sorry for not answering sooner. I totally forgot about it.
Second, thanks for the failing test. This helped a lot in pinpointing the problem.
Third, the issue is due to the fact that the schema isn't specified. As a result, we're calling ``new DataSourceDatabaseTester(dataSource, "")``  instead of  ``new DataSourceDatabaseTester(dataSource, null)``. 

I changed that and also added your test.
