### ISSUE TITLE
Separate Spock.DbUnit content for each case in one Specification

### ISSUE THREAD

**Issue by arthurdn** [janbols/spock-dbunit#2]
Content is called for all cases.

How specify it for each case?

```
    @DbUnit def content =  {
       CATEGORY(CATEGORY_ID: 1L, CATEGORY_NAME: "N", CATEGORY_IMAGE:"I")
    }
```

**Comment by janbols** [comment]
Hi  @arthurdn , indeed, this is currently not foreseen. However, it shouldn't be too difficult to add this. 

How would you see this happening? Add a @DbUnit annotation above the feature containing a content field with the closure? Like in the following...

``` groovy
    @DbUnit(content = {
        User(id: 1, name: 'janbols')
    })
    def "test"() {
        when:
        def result = new Sql(dataSource).firstRow("select * from User where name = 'janbols'")
        then:
        result.id == 1
    }
```
