### ISSUE TITLE
Single table inheritance: not common fields are not filled

### ISSUE THREAD

**Issue by vargaendre** [janbols/spock-dbunit#3]
Hi,
first, let me say thank you for this cool lib.
I tried to create different child entities of the same parent with annotations, but could not set non-common arguments.
So in my case, there is a User parent class, an EndUser and a ManagerUser children. I tried to make one EndUser and two ManagerUser instances. The latter would need some attributes filled which are not present in the first. So I am adding the attributes for the ManagerUser, but not for the EndUser. This way the attribute value is not set in the DB (it is null). If I only want to create ManagerUser instances I can add the attribute if I add to all of the created ones.
Is this a bug or am I doing something wrongly?
Your help is very much appreciated!

**Comment by janbols** [comment]
Hi, I'm not sure I completely understand your problem without a concrete example, but perhaps it has to do with the fact that dbunit creates its tables based on the first row. So if the first item contains Enduser containing less fields, it will base the table on that. See http://dbunit.sourceforge.net/faq.html#differentcolumnnumber for further explanation. 
Please let me know when I'm missing the ball completely.
Best regards
Jan

**Comment by vargaendre** [comment]
Hi,
thank you very much for the quick answer!
I read about this first row thing, tried it, but had an issue still. But now I tried it again and it seems to work perfectly.
Thank you again!
