### ISSUE TITLE
Problem with DB schema

### ISSUE THREAD

**Issue by cbrani** [janbols/spock-dbunit#6]
Hi Jan,

I need to set the schema of an oracle database.
There is the posibility to do it with the configure closure like this

`    
@DbUnit(configure = { IDatabaseTester dbTester ->
        dbTester.setSchema(config.getString("schema"))
 })
`

but this approach is deprecated in dbunit
**since 2.4.3 Should not be used anymore. Every concrete IDatabaseTester implementation that needs a schema has the possibility to set it somehow in the constructor**

Would it be possible that the annotation gets an extra field to specify a schema?

**Comment by janbols** [comment]
Hi @cbrani , sorry for the late reply. I'll see what I can do if I get the time.
Greetings
Jan

**Comment by janbols** [comment]
Added extra field in @DbUnit allowing you to specify the schema to use.
Due in version 0.3

**Comment by cbrani** [comment]
Hi @janbols,
thank you for the quick fix :-)

Have you thought about my other feature request? Is it doable as well?

Greetings
Carsten

**Comment by janbols** [comment]
Yes it's doable but it will need a bit of refactoring. I'll get to it when I have some time.
