### ISSUE TITLE
Feature request: annotation @DbUnit per feature

### ISSUE THREAD

**Issue by cbrani** [janbols/spock-dbunit#7]
It would be nice to have the possibility to annotate a feature with @DbUnit. 
It would allow e.g. that only one feature uses dbunit or that several feature could have their individual dbunit instruction set.

**Comment by janbols** [comment]
It's doable and somthing I've been thinking about myself.

**Comment by janbols** [comment]
Hi @cbrani , in version 0.3 you can specify a `DbUnit` annotation on each feature. Please see the readme for more information. Please take a look at it and let me know if that's what you had in mind.

**Comment by cbrani** [comment]
Hi @janbols ,
Great, yes that's what I had in mind 👍 

I came up with some further notes nevertheless ;-)

If the schema attribute would be a Closure it would be more flexible. In our test environment we have user specific settings and one of them is the used DB schema. With a closure you could reference the config variable and extract the schema.

Not all of the features in our specification classes need a dbunit setup. The current workaround is that I setup the field annotation with an empty content and annotate the features which definitely need a dbunit setup with an extra @DbUnit. I don't know yet if that is a performance penalty but it works. Do you think it would be an idea to have a sort of a skip annotation for a feature? Or another option would be to omit the field annotation and only use the feature annotation in that case (which doesn't work right now. I tried ;-) )
