### ISSUE TITLE
Multiple @DbUnit for specific feature.

### ISSUE THREAD

**Issue by Kanti1702** [janbols/spock-dbunit#8]
I have legacy db in which there are some tables without Primary key and some with PK, I know that for table with PK i can use DatabaseOperation.INSERT and tables without PK I can use DatabaseOperation.REFRESH, but for this I need to write 2 def conten{...}, but it's not allow to write, so what should I do? 

In spec file how can I handle this scenario?

**Comment by janbols** [comment]
Hi @Kanti1702 , I don't know how to handle this situation. How would you handle this using plain dbunit? Perhaps http://dbunit.wikidot.com/noprimarykeytable can give you some inspiration on how to move forward.
